import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 0: Orientation',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-ros2-basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: '03-nvidia-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        {
          type: 'autogenerated',
          dirName: '04-vla-models',
        },
      ],
    },
  ],
};

export default sidebars;
